/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Project = IDL.Record({
  'title' : IDL.Text,
  'githubLink' : IDL.Text,
  'description' : IDL.Text,
});
export const Contact = IDL.Record({
  'linkedIn' : IDL.Text,
  'email' : IDL.Text,
  'github' : IDL.Text,
});

export const idlService = IDL.Service({
  'addProject' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
  'getAllProjects' : IDL.Func([], [IDL.Vec(Project)], ['query']),
  'getContactInfo' : IDL.Func([], [Contact], ['query']),
  'getProject' : IDL.Func([IDL.Text], [Project], ['query']),
  'removeProject' : IDL.Func([IDL.Text], [], []),
  'updateProject' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Project = IDL.Record({
    'title' : IDL.Text,
    'githubLink' : IDL.Text,
    'description' : IDL.Text,
  });
  const Contact = IDL.Record({
    'linkedIn' : IDL.Text,
    'email' : IDL.Text,
    'github' : IDL.Text,
  });
  
  return IDL.Service({
    'addProject' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
    'getAllProjects' : IDL.Func([], [IDL.Vec(Project)], ['query']),
    'getContactInfo' : IDL.Func([], [Contact], ['query']),
    'getProject' : IDL.Func([IDL.Text], [Project], ['query']),
    'removeProject' : IDL.Func([IDL.Text], [], []),
    'updateProject' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
  });
};

export const init = ({ IDL }) => { return []; };